# frozen_string_literal: true

require 'test_helper'
require 'open3'
require 'pathname'
require_relative 'support/site_build_helper'

class SiteJavascriptTest < Minitest::Test
  def setup
    @node_available = node_available?
    SiteBuildHelper.ensure_site_built if @node_available
  end

  def test_generated_javascript_is_well_formed
    skip 'Node.js is not available on PATH' unless @node_available

    destination = SiteBuildHelper.destination
    js_files = Dir.glob(File.join(destination, '**', '*.js'))
    skip 'No JavaScript files generated by Jekyll' if js_files.empty?

    errors = js_files.filter_map { |path| javascript_error(path) }

    assert_empty errors, format_errors(errors)
  end

  private

  def javascript_error(path)
    _stdout, stderr, status = Open3.capture3('node', '--check', path)
    return nil if status.success?

    {
      path: relative_path(path),
      message: stderr.strip.empty? ? 'Unknown syntax error' : stderr.strip
    }
  end

  def relative_path(path)
    Pathname.new(path).relative_path_from(Pathname.new(SiteBuildHelper.destination)).to_s
  end

  def format_errors(errors)
    errors.map { |err| "#{err[:path]}: #{err[:message]}" }.join("\n")
  end

  def node_available?
    system('node', '--version', out: File::NULL, err: File::NULL)
  end
end
