# frozen_string_literal: true

require 'test_helper'
require 'json'
require 'pathname'
require_relative 'support/site_build_helper'

class SiteJsonTest < Minitest::Test
  def setup
    SiteBuildHelper.ensure_site_built
  end

  def test_generated_json_is_well_formed
    destination = SiteBuildHelper.destination
    json_files = Dir.glob(File.join(destination, '**', '*.json'))
    skip 'No JSON files generated by Jekyll' if json_files.empty?

    errors = json_files.filter_map { |path| parse_error(path) }
    assert errors.empty?, errors.join("\n")
  end

  private

  def parse_error(path)
    JSON.parse(File.read(path))
    nil
  rescue JSON::ParserError => e
    "#{relative_path(path)}: #{e.message}"
  end

  def relative_path(path)
    Pathname.new(path).relative_path_from(Pathname.new(SiteBuildHelper.destination)).to_s
  end
end
