---
default:
  test: <tmp>         # create a temp repo automatically
events:
  test: <tmp>
  development: "."
  production: "."
locations:
  test: <tmp>
  development: "."
  production: "."
news:
  test: <tmp>
  development: "."
  production: "."
organizations:
  test: <tmp>
  development: "."
  production: "."
topics:
  test: <tmp>
  development: "."
  production: "."
images:
  test: <tmp>
  development: "."
  production: "."
