---
default:
  development: "."
  production: "."
  test: <tmp>
events:
  development: "."
  production: "."
  test: <tmp>
images:
  development: "."
  production: "."
  test: <tmp>
locations:
  development: "."
  production: "."
  test: <tmp>
posts:
  development: "."
  production: "."
  test: <tmp>
organizations:
  development: "."
  production: "."
  test: <tmp>
topics:
  development: "."
  production: "."
  test: <tmp>
