plugins:
  - rubocop-minitest
AllCops:
  NewCops: enable
  Include:
    - 'bin/**/*.rb'
    - 'lib/**/*.rb'
    - 'script/**/*.rb'
    - 'Rakefile'
Layout/LineLength:
    Max: 160
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ParameterLists:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Style/Documentation:
  Enabled: false
